language: python
matrix:
  include:
  - env: TARGET=py2
  - env: TARGET=py3
  - env: TARGET=mypy
  allow_failures:
  - env: TARGET=py3
  - env: TARGET=mypy
sudo: required
services:
  - docker
install:
    - true
script:
- docker build . -f .travis/${TARGET}.docker
deploy:
  provider: pypi
  user: Fil8
  password:
secure: V/kEtdBre9XrAfHh0vwoQsL+xxYsMsSGOIhyAu39Zy6u7a+xlc4o9CzZorJQ7DBIeQUOHFKolLMvPUQvnkfLEeJeqmOH8yNLS3hMvWsjeRz2N20dp4nQynQnWFOMYNRibGJqeIAa1VyHGIrFAvdWahrC3qGwkWgAZCID1J0tbNP0kop6tFQ1KtKUdBSQqDntAgcvCuYdeWDPetUfFmfdUSG1lBT0bcisxcfGYzoLis9UrLzNr6pPQ3FDrC+nkVzTyML9lCz7DWWMybjpxkobnb4LpY2FOLzFiyWs2t4esv/6tEGgI9rG6HJS6VdgR9MG3LDlCpQh2zrvv0TddiCKhH0UXr3LAvaGfM3mUXdRU1ANX+lSmDyMBWNBGnP2uADW7nHXS60YLFRwRTIMMrzohRVe3tD0wxfUS2MAKdEaRPA0r5fVxCji+YFNsk1z+YlB/qUFsRwEeOgZ7ntf+XCnTDXDIkhntqtxB0oPIt5TQPLvvgTUNbDcaLds8P0hYQlYptqt13euRfA1J4FX8CwsnKyBe2b3LCuEBqo3az0jO1kuwIu8+z2JO93gmsy76N0yDjEyasRyC5XoLC4jJpbhfzseUXckIUQW/qY/G/LH2lMkzh9VM0BTCmutQYHgPNb+MFdeQR5pZqct6fX+1EPaN72GaBfT+OoJq6vQVts4gkE=
  on:
    tags: true
    repo: Fil8/SHARPener
